# Generated by Django 3.2.7 on 2021-10-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Staff'), (2, 'Student')], default=2, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
