# Generated by Django 3.2.7 on 2021-10-05 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0002_auto_20211005_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='motivation_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
