# Generated by Django 3.2.7 on 2021-10-06 06:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_motivation_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
