# Generated by Django 3.2.7 on 2021-10-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211006_0918'),
        ('student', '0004_alter_motivation_image'),
    ]

    operations = [
    ]
