# Generated by Django 3.2.7 on 2021-10-06 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_merge_20211006_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivation',
            name='likes',
            field=models.ManyToManyField(related_name='motivation_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.studentuser'),
            preserve_default=False,
        ),
    ]
