# Generated by Django 3.2.7 on 2021-10-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211006_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
