# Generated by Django 3.2.7 on 2021-10-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_merge_20211006_1111'),
        ('student', '0006_auto_20211006_1525'),
    ]

    operations = [
    ]
