# Generated by Django 3.2.7 on 2021-10-10 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_studentuser_is_superuser'),
        ('student', '0007_merge_20211007_1217'),
    ]

    operations = [
    ]
