# Generated by Django 3.2.7 on 2021-10-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_reviewthread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='motivatation',
            new_name='motivation',
        ),
    ]
